### ISSUE TITLE
Issues with redcap 6.15.0

### ISSUE THREAD

**Issue by vatese** [lsgs/redcap-longitudinal-reports#1]
The layout of the longitudinal reports page is altered when updating to version 6.15.0

**Comment by vatese** [comment]
My bad, some files had no read permissions.

**Comment by lsgs** [comment]
No worries @vatese. I had someone else reporting problems after the upgraded to 6.15 so I will pass on the potential solution. I've been testing on 6.16 preparing for an upgrade and am not seeing anything amiss.
