### ISSUE TITLE
Any plans to turn this into a module?

### ISSUE THREAD

**Issue by pbchase** [lsgs/redcap-longitudinal-reports#2]
Are there any plans to turn this into an external module? If not, I have resources I could apply to the task.

**Comment by lsgs** [comment]
Yes Phillip. This is most definitely on the list too.  I'm hoping Jan will be quieter around here and I will have some time to work on a few things like this that are on the list. It may well be useful to have some help with this one. It'll be a big job!

**Comment by skhalliday** [comment]
Hi, are there any updates about turning this into a module? Thanks

**Comment by pbchase** [comment]
> Hi, are there any updates about turning this into a module? Thanks

We have our own variant of this module in production at the University of Florida. We're dealing with a nasty bug at the moment, but expect to fix it soon. Our work is at https://github.com/ctsit/record_autonumbering. @lsgs, if you don't want to publish this, we'd be happy to.

**Comment by lsgs** [comment]
Hello Philip,

I hope all is well with you. Which do you mean? lsgs/redcap-longitudinal-reports or lsgs/redcap-record-autonumbering?

The answer is yes to both. Do you think the autonumbering one is complete enough? I would like to solve the problem with it with records created by the “Randomize” process (I have another idea to investigate for that at some point), and there is also the question of how to propagate any custom classes people have into new versions.

The longitudinal reports thing is very high on my list and I’ve made some progress on it. I’m basically integrating a “rehaping” option into the built-in reports page...

Regards,
Luke

**Comment by pbchase** [comment]
> I hope all is well with you. Which do you mean? lsgs/redcap-longitudinal-reports or lsgs/redcap-record-autonumbering?

I am commenting on the wrong module. Sorry about the confusion. I'll send you an email privately about our thoughts on record_autonumbering

**Comment by bfulcher-monash** [comment]
Hi, just wondering if there's been any progress on turning this into an external module? Thank you

**Comment by lsgs** [comment]
@pbchase, @skhalliday, @bfulcher-monash: [https://github.com/lsgs/redcap-extended-reports/](https://github.com/lsgs/redcap-extended-reports/) is now released in the REDCap Repo
