### ISSUE TITLE
Users not allowed to access page unless they have report editing or data export permissions

### ISSUE THREAD

**Issue by notallthere2day** [lsgs/redcap-longitudinal-reports#3]
Hi,
I just had a complaint from a user that they couldn't view the Longitudinal reports page. It seems that in order to view the page, you have to have either report editing or data export permissions. Is that intentional? I've modified line 16 of index.php on our install as follows:
//if (!$Proj->longitudinal || ($user_rights['data_export_tool'] == "0" && $user_rights['reports'] == "0")) {
if (!$Proj->longitudinal) {
This seems to work fine. Please let me know if I've missed something!
Cheers

**Comment by lsgs** [comment]
I think you should at least leave in the check for permission to access the Data Export module. The way you have it lets all project users access the report, which may be inappropriate for some projects.

```if (!$Proj->longitudinal || $user_rights['reports'] == "0") {```
